#!/bin/bash

# Load sxhkd (only if it is not running already)
pgrep -x sxhkd > /dev/null || sxhkd -c "$HOME/cfg/bspwm/sxhkdrc" &

# Other things to execute at startup
xsetroot -cursor_name miku-cursor-linux
feh --nofehbg --bg-fill "$HOME/img/veri.png" &
export _JAVA_AWT_WM_NONREPARENTING=1

sh -c "$HOME/cfg/bspwm/audio.sh" &
sh -c "$HOME/layout.sh" &

xclip &
#picom &

# How many desktops & Desktop names
bspc monitor -d 1 2 3

# Window rules
bspc rule -a st follow=true focus=true
bspc rule -a eww floating=true
bspc rule -a gscreenshot floating=true
bspc rule -a feh floating=true focus=true

#Borders
bspc config border_width 0
pkill borders ; borders &

# Other settings
bspc config left_padding 0
bspc config window_gap 15
bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer true